Run promises in order
FlowFuse/driver-k8s pull request #115
Opened 2023-09-25 10:49 UTC by hardillb

## Description

possible for creating/deleting k8s artefacts to fail if done out of order or too quickly.

## Related Issue(s)

#114

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-10-11 16:36 UTC, elenaviter commented
Hello @hardillb,
I've opened followup [PR](https://github.com/FlowFuse/driver-k8s/pull/118) on this same branch.
The code was staged on our systems and shown the problems it address are solved:
- suspend/start project is not guaranteed to succeed
- projects auth token deteriorates after FF upgrade 

We are aiming to integrate it at the earliest convenience. 
Thank you in advance for considering our request! We are looking forward to your valuable feedback.

2023-10-13 10:02 UTC, elenaviter approved these changes

2023-10-13 10:32 UTC, hardillb commented
I've tested this locally on my K8s rig and it looks good so far.

2023-10-16 10:39 UTC, hardillb commented
@ppawlowski when you get moment can you review this so I can deploy it to staging for more testing. Thanks

2023-10-18 09:01 UTC, knolleary requested changes
Spotted some intervals that wouldn't be stopped in case of an error.

2023-10-18 09:01 UTC, knolleary commented on kubernetes.js
> +                }
```suggestion
                if (counter > this._k8sRetries) {
                    clearInterval(pollInterval)
                    this._app.log.error(`[k8s] Project ${project.id} - timeout waiting for Deployment`)
                    reject(new Error('Timed out to creating Deployment'))
                }
```

2023-10-18 13:34 UTC, knolleary approved these changes

2023-10-18 13:34 UTC, merged